import React from 'react';

// --- COLOR CONSTANTS ---
export const mainTextColor = '#343a40'; // Dark grey for most primary text
export const lightTextColor = '#6c757d'; // Lighter grey for secondary text/details
export const brandColor = '#0056b3'; // Primary brand blue
export const accentColor = '#007bff'; // Accent blue for links, active states
export const successColor = '#28a745';
export const warningColor = '#ffc107';
export const dangerColor = '#dc3545';
export const infoColor = '#17a2b8';
export const white = 'white';
export const lightBackground = '#f0f2f5'; // Overall app background
export const mediumBackground = '#f8f9fa'; // For sections like detail items, column headers
export const lighterBackground = '#e7f3ff'; // For active sidebar button, today's calendar day light background
export const lightBorder = '#eee';
export const mediumBorder = '#e9ecef';
export const darkBorder = '#ced4da';

// --- STYLES ---
export const styles: { [key: string]: React.CSSProperties } = {
  body: { fontFamily: "'Cairo Play', sans-serif", backgroundColor: lightBackground, color: mainTextColor, margin: 0, padding: 0, },
  appContainer: { display: 'flex', direction: 'rtl' },
  sidebar: { width: '260px', height: '100vh', position: 'fixed', top: 0, right: 0, backgroundColor: white, boxShadow: '-2px 0 10px rgba(0,0,0,0.05)', display: 'flex', flexDirection: 'column', padding: '20px', zIndex: 100, boxSizing: 'border-box' },
  sidebarHeader: { textAlign: 'center', marginBottom: '30px', paddingBottom: '20px', borderBottom: `1px solid ${lightBorder}` },
  sidebarTitle: { fontSize: '26px', fontWeight: 700, color: brandColor, margin: '0 0 5px 0', fontFamily: "'Cairo Play', sans-serif" },
  sidebarSubtitle: { fontSize: '13px', color: lightTextColor, margin: 0, fontFamily: "'Cairo Play', sans-serif" },
  sidebarBrand: { fontSize: '22px', fontWeight: 'bold', color: mainTextColor, marginTop: '15px', fontFamily: "'Cairo Play', sans-serif" },
  sidebarNav: { display: 'flex', flexDirection: 'column', gap: '10px' },
  sidebarNavButton: { display: 'flex', alignItems: 'center', gap: '15px', padding: '15px 20px', fontSize: '16px', fontWeight: 700, border: 'none', borderRadius: '8px', cursor: 'pointer', textAlign: 'right', backgroundColor: 'transparent', color: mainTextColor, transition: 'all 0.3s ease', fontFamily: "'Cairo Play', sans-serif", },
  sidebarNavButtonActive: { backgroundColor: lighterBackground, color: brandColor },
  mainContent: { flex: 1, marginRight: '260px', padding: '30px', backgroundColor: lightBackground, minHeight: '100vh' },
  viewHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px', flexWrap: 'wrap', gap: '15px' },
  viewTitle: { fontSize: '28px', fontWeight: 700, color: mainTextColor, margin: 0, fontFamily: "'Cairo Play', sans-serif" },
  viewHeaderActions: { display: 'flex', alignItems: 'center', gap: '15px', flexWrap: 'wrap' },
  searchInput: { padding: '12px 15px', fontSize: '16px', border: `1px solid ${darkBorder}`, borderRadius: '6px', width: '300px', fontFamily: "'Cairo Play', sans-serif", boxSizing: 'border-box', color: mainTextColor },
  addButton: { padding: '12px 25px', fontSize: '16px', backgroundColor: successColor, color: white, border: 'none', borderRadius: '6px', cursor: 'pointer', transition: 'background-color 0.3s ease', display: 'flex', alignItems: 'center', gap: '8px', justifyContent: 'center', boxSizing: 'border-box', fontFamily: "'Cairo Play', sans-serif" },
  patientGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(380px, 1fr))', gap: '20px', },
  patientCard: { backgroundColor: white, borderRadius: '8px', boxShadow: '0 2px 8px rgba(0,0,0,0.1)', padding: '20px', display: 'flex', flexDirection: 'column', gap: '15px', },
  patientCardHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: `1px solid ${lightBorder}`, paddingBottom: '10px', },
  patientName: { fontSize: '22px', fontWeight: 700, color: mainTextColor, margin: '0 0 5px 0', fontFamily: "'Cairo Play', sans-serif" },
  patientComplaint: { fontSize: '14px', color: lightTextColor, marginTop: '4px', fontFamily: "'Cairo Play', sans-serif" },
  patientActions: { display: 'flex', gap: '10px', },
  iconButton: { background: 'none', border: 'none', cursor: 'pointer', padding: '5px', fontSize: '18px', color: mainTextColor, fontFamily: "'Cairo Play', sans-serif" },
  patientDetailsGrid: { display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '10px 15px', },
  patientContactGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px 15px', marginTop: '10px', paddingTop: '10px', borderTop: `1px solid ${lightBorder}` },
  contactAddress: { gridColumn: '1 / -1' },
  detailItem: { backgroundColor: mediumBackground, padding: '8px', borderRadius: '4px', fontSize: '14px', fontFamily: "'Cairo Play', sans-serif", color: mainTextColor },
  detailLabel: { fontWeight: 700, color: mainTextColor, marginInlineEnd: '5px', fontFamily: "'Cairo Play', sans-serif" },
  notesSection: { gridColumn: '1 / -1', backgroundColor: mediumBackground, padding: '10px', borderRadius: '4px', fontSize: '14px', whiteSpace: 'pre-wrap', wordBreak: 'break-word', fontFamily: "'Cairo Play', sans-serif", color: mainTextColor },
  treatmentSection: { borderTop: `1px solid ${lightBorder}`, paddingTop: '15px', },
  treatmentHeader: { fontSize: '18px', fontWeight: 700, marginBottom: '10px', color: mainTextColor, display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontFamily: "'Cairo Play', sans-serif" },
  treatmentLog: { border: `1px solid ${mediumBorder}`, borderRadius: '6px', padding: '12px', marginBottom: '10px', backgroundColor: white, },
  logDate: { fontWeight: 700, color: mainTextColor, marginBottom: '8px', fontSize: '15px', fontFamily: "'Cairo Play', sans-serif" },
  logDetails: { fontSize: '14px', display: 'flex', flexDirection: 'column', gap: '5px', fontFamily: "'Cairo Play', sans-serif", color: mainTextColor },
  toggleHistoryButton: { background: 'none', border: 'none', color: accentColor, cursor: 'pointer', fontSize: '14px', padding: '5px 0', marginTop: '10px', textAlign: 'center', width: '100%', fontWeight: 700, fontFamily: "'Cairo Play', sans-serif", },
  modalOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0, 0, 0, 0.6)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1000, },
  modalContent: { backgroundColor: white, padding: '30px', borderRadius: '8px', width: '90%', maxWidth: '600px', maxHeight: '90vh', overflowY: 'auto', position: 'relative' },
  modalTitle: { fontSize: '24px', fontWeight: 700, marginBottom: '20px', color: brandColor, fontFamily: "'Cairo Play', sans-serif" },
  form: { display: 'flex', flexDirection: 'column', gap: '15px', },
  formRow: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px' },
  formGroup: { display: 'flex', flexDirection: 'column', gap: '5px', },
  formGroupHorizontal: { display: 'flex', alignItems: 'center', gap: '10px' },
  label: { fontWeight: 700, fontSize: '14px', fontFamily: "'Cairo Play', sans-serif", color: mainTextColor },
  input: { padding: '10px', border: `1px solid ${darkBorder}`, borderRadius: '4px', fontSize: '16px', fontFamily: "'Cairo Play', sans-serif", boxSizing: 'border-box', color: mainTextColor },
  colorInput: { padding: '5px', border: `1px solid ${darkBorder}`, borderRadius: '4px', width: '100%', height: '45px', cursor: 'pointer', boxSizing: 'border-box', fontFamily: "'Cairo Play', sans-serif" },
  textarea: { padding: '10px', border: `1px solid ${darkBorder}`, borderRadius: '4px', fontSize: '16px', minHeight: '80px', resize: 'vertical', fontFamily: "'Cairo Play', sans-serif", color: mainTextColor },
  select: { padding: '10px', border: `1px solid ${darkBorder}`, borderRadius: '4px', fontSize: '16px', backgroundColor: white, fontFamily: "'Cairo Play', sans-serif", boxSizing: 'border-box', color: mainTextColor },
  formActions: { display: 'flex', justifyContent: 'flex-end', gap: '10px', marginTop: '10px', },
  button: { padding: '10px 20px', fontSize: '16px', border: 'none', borderRadius: '6px', cursor: 'pointer', transition: 'background-color 0.3s ease', fontFamily: "'Cairo Play', sans-serif", },
  buttonPrimary: { backgroundColor: accentColor, color: white, },
  buttonSecondary: { backgroundColor: lightTextColor, color: white, },
  buttonInfo: { backgroundColor: infoColor, color: white, },
  closeButton: { position: 'absolute', top: '15px', left: '15px', background: 'none', border: 'none', fontSize: '24px', cursor: 'pointer', color: mainTextColor, fontFamily: "'Cairo Play', sans-serif" },
  emptyState: { textAlign: 'center', padding: '50px', backgroundColor: white, borderRadius: '8px', fontFamily: "'Cairo Play', sans-serif" },
  emptyStateText: { fontSize: '18px', color: lightTextColor, fontFamily: "'Cairo Play', sans-serif" },
  dashboardGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))', gap: '20px', marginBottom: '30px' },
  statCard: { backgroundColor: white, padding: '25px', borderRadius: '8px', boxShadow: '0 2px 4px rgba(0,0,0,0.1)', textAlign: 'center', borderTop: `4px solid ${accentColor}` },
  statCardTitle: { fontSize: '18px', color: lightTextColor, margin: '0 0 10px 0', fontWeight: 700, fontFamily: "'Cairo Play', sans-serif" },
  statCardValue: { fontSize: '40px', fontWeight: 700, color: brandColor, margin: 0, fontFamily: "'Cairo Play', sans-serif" },
  section: { backgroundColor: white, padding: '25px', borderRadius: '8px', boxShadow: '0 2px 4px rgba(0,0,0,0.1)', marginBottom: '30px' },
  list: { listStyle: 'none', padding: 0, margin: 0 },
  listItem: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '15px 0', borderBottom: `1px solid ${mediumBorder}` },
  listItemName: { fontWeight: 700, fontSize: '16px', fontFamily: "'Cairo Play', sans-serif", color: mainTextColor },
  listItemDetails: { color: lightTextColor, fontSize: '14px', fontFamily: "'Cairo Play', sans-serif" },
  doctorCard: { backgroundColor: white, borderRadius: '8px', boxShadow: '0 2px 8px rgba(0,0,0,0.1)', padding: '20px', display: 'flex', flexDirection: 'column', gap: '15px', borderTop: '5px solid transparent' },
  doctorName: { fontSize: '22px', fontWeight: 700, color: mainTextColor, margin: '10px 0 5px 0', textAlign: 'center', fontFamily: "'Cairo Play', sans-serif" },
  doctorSpecialty: { fontSize: '16px', color: accentColor, fontWeight: 700, marginBottom: '15px', textAlign: 'center', fontFamily: "'Cairo Play', sans-serif" },
  doctorContact: { display: 'flex', flexDirection: 'column', gap: '5px', fontSize: '14px', textAlign: 'center', fontFamily: "'Cairo Play', sans-serif", color: lightTextColor },
  doctorActions: { marginTop: '15px', display: 'flex', justifyContent: 'center', gap: '10px' },
  appointmentList: { display: 'flex', flexDirection: 'column', gap: '0' },
  dayGroup: { marginBottom: '20px', backgroundColor: white, borderRadius: '8px', boxShadow: '0 2px 4px rgba(0,0,0,0.05)', overflow: 'hidden' },
  dayGroupHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '15px 20px', backgroundColor: mediumBackground, border: 'none', width: '100%', cursor: 'pointer', textAlign: 'right', fontSize: '18px', fontWeight: 700, color: mainTextColor, borderBottom: `1px solid ${mediumBorder}`, fontFamily: "'Cairo Play', sans-serif", },
  dayGroupToggleIcon: { fontSize: '14px', transition: 'transform 0.2s ease-in-out', fontFamily: "'Cairo Play', sans-serif", color: mainTextColor },
  dayGroupContent: { padding: '0' },
  appointmentItem: { backgroundColor: white, borderRadius: '0px', padding: '20px', display: 'grid', gridTemplateColumns: '1fr 1fr 1fr auto', alignItems: 'center', gap: '15px', boxShadow: 'none', borderInlineStart: '5px solid #ccc', borderBottom: `1px solid ${lightBackground}`, },
  appointmentItemInDoctorView: { backgroundColor: white, borderRadius: '0px', padding: '20px', display: 'grid', gridTemplateColumns: '1fr 1.5fr auto', alignItems: 'center', gap: '15px', boxShadow: 'none', borderBottom: `1px solid ${lightBackground}`, },
  appointmentTime: { fontSize: '20px', fontWeight: 700, color: accentColor, fontFamily: "'Cairo Play', sans-serif" },
  appointmentPatient: { fontWeight: 700, fontFamily: "'Cairo Play', sans-serif", color: mainTextColor },
  appointmentDoctor: { color: mainTextColor, display: 'flex', alignItems: 'center', gap: '8px', fontFamily: "'Cairo Play', sans-serif" },
  appointmentStatus: { padding: '5px 12px', borderRadius: '15px', fontSize: '12px', fontWeight: 700, color: white, textAlign: 'center', fontFamily: "'Cairo Play', sans-serif" },
  statusScheduled: { backgroundColor: warningColor },
  statusCompleted: { backgroundColor: successColor },
  statusCanceled: { backgroundColor: dangerColor },
  appointmentActions: { display: 'flex', gap: '10px' },
  filtersContainer: { display: 'flex', gap: '10px', alignItems: 'center', flexWrap: 'wrap', backgroundColor: white, padding: '15px', borderRadius: '8px', marginBottom: '20px', boxShadow: '0 2px 4px rgba(0,0,0,0.05)' },
  // Calendar styles
  calendarContainer: { backgroundColor: white, padding: '20px', borderRadius: '8px', boxShadow: '0 2px 4px rgba(0,0,0,0.1)' },
  calendarHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px', fontFamily: "'Cairo Play', sans-serif", color: mainTextColor },
  calendarNavButton: { background: 'none', border: `1px solid ${darkBorder}`, borderRadius: '50%', width: '30px', height: '30px', cursor: 'pointer', fontFamily: "'Cairo Play', sans-serif", color: mainTextColor },
  calendarGrid: { display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: '5px', textAlign: 'center' },
  calendarDayName: { fontWeight: 700, fontSize: '12px', color: lightTextColor, fontFamily: "'Cairo Play', sans-serif" },
  calendarDay: { border: `1px solid ${mediumBorder}`, borderRadius: '4px', minHeight: '100px', padding: '5px', cursor: 'pointer', transition: 'background-color 0.2s', position: 'relative' },
  calendarDayOtherMonth: { backgroundColor: mediumBackground, color: lightTextColor },
  calendarDayToday: { borderColor: accentColor, backgroundColor: lighterBackground },
  calendarDayNumber: { fontSize: '14px', fontWeight: 700, fontFamily: "'Cairo Play', sans-serif", color: mainTextColor },
  appointmentIndicatorsContainer: { position: 'absolute', bottom: '8px', right: '8px', display: 'flex', gap: '4px' },
  appointmentColorDot: { width: '8px', height: '8px', borderRadius: '50%' },
  viewToggle: { display: 'flex', gap: '5px', border: `1px solid ${accentColor}`, borderRadius: '6px', padding: '4px' },
  toggleButton: { padding: '8px 15px', border: 'none', borderRadius: '4px', cursor: 'pointer', backgroundColor: 'transparent', color: accentColor, fontFamily: "'Cairo Play', sans-serif" },
  toggleButtonActive: { backgroundColor: accentColor, color: white },
  dayModalList: { listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '10px' },
  dayModalItem: { border: `1px solid ${lightBorder}`, padding: '15px', borderRadius: '6px' },
  dayModalTime: { fontWeight: 'bold', color: brandColor, fontSize: '18px', fontFamily: "'Cairo Play', sans-serif" },
  dayModalPatient: { marginTop: '5px', fontWeight: 'bold', fontFamily: "'Cairo Play', sans-serif", color: mainTextColor },
  dayModalReason: { marginTop: '5px', color: lightTextColor, fontSize: '14px', fontFamily: "'Cairo Play', sans-serif" },
  dataManagementActions: { display: 'flex', gap: '15px', alignItems: 'center', justifyContent: 'center', paddingTop: '10px' },
  reminderIcon: { fontSize: '16px', marginInlineStart: '10px' },
  reminderSent: { color: successColor, cursor: 'help' },
  reminderPending: { color: lightTextColor, cursor: 'help' },
  settingsSection: { display: 'flex', gap: '15px', alignItems: 'center', flexWrap: 'wrap' },
  scheduleModalItem: { border: `1px solid ${lightBorder}`, padding: '15px', borderRadius: '6px', display: 'grid', gridTemplateColumns: '150px 1fr', gap: '15px', alignItems: 'center' },
  scheduleModalDateTime: { fontWeight: 'bold', color: brandColor, fontSize: '16px', fontFamily: "'Cairo Play', sans-serif" },
  scheduleModalPatientInfo: { display: 'flex', flexDirection: 'column', gap: '5px' },
  // Board styles
  boardContainer: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '20px', alignItems: 'flex-start' },
  boardColumn: { backgroundColor: mediumBackground, borderRadius: '8px', padding: '15px', display: 'flex', flexDirection: 'column', gap: '15px', minHeight: '400px' },
  boardColumnHeader: { paddingBottom: '10px', borderBottom: '2px solid', marginBottom: '5px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', color: mainTextColor },
  boardColumnTitle: { fontSize: '18px', fontWeight: 700, fontFamily: "'Cairo Play', sans-serif", color: mainTextColor },
  boardColumnCount: { fontSize: '16px', fontWeight: 700, backgroundColor: lightBorder, color: mainTextColor, borderRadius: '50%', width: '28px', height: '28px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: "'Cairo Play', sans-serif" },
  boardCard: { backgroundColor: white, borderRadius: '6px', boxShadow: '0 1px 3px rgba(0,0,0,0.1)', padding: '15px', borderInlineStart: '5px solid' },
  boardCardTime: { fontSize: '18px', fontWeight: 700, marginBottom: '8px', fontFamily: "'Cairo Play', sans-serif", color: mainTextColor },
  boardCardPatient: { fontWeight: 700, marginBottom: '4px', fontFamily: "'Cairo Play', sans-serif", color: mainTextColor },
  boardCardReason: { fontSize: '14px', color: lightTextColor, marginBottom: '10px', fontFamily: "'Cairo Play', sans-serif" },
  boardCardDoctor: { fontSize: '13px', color: lightTextColor, display: 'flex', alignItems: 'center', gap: '8px', fontFamily: "'Cairo Play', sans-serif" },
  financialSummary: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px', padding: '10px', backgroundColor: mediumBackground, borderRadius: '6px', textAlign: 'center' },
  financialLabel: { fontSize: '14px', color: lightTextColor, fontWeight: 'bold' },
  financialValue: { fontSize: '20px', fontWeight: 700 },
  paymentStatus: { padding: '3px 10px', borderRadius: '12px', fontSize: '12px', fontWeight: 'bold', color: white },
  paymentStatusPaid: { backgroundColor: successColor },
  paymentStatusUnpaid: { backgroundColor: dangerColor },
  markAsPaidButton: { padding: '5px 10px', fontSize: '12px', backgroundColor: successColor, color: white, border: 'none', borderRadius: '4px', cursor: 'pointer', transition: 'background-color 0.2s ease', },
  logFinancials: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '10px', paddingTop: '10px', borderTop: `1px solid ${lightBorder}` },

  // --- MOBILE STYLES ---
  sidebarMobile: { transform: 'translateX(100%)', transition: 'transform 0.3s ease-in-out', zIndex: 1100, width: '280px' },
  sidebarMobileOpen: { transform: 'translateX(0)' },
  mainContentMobile: { marginRight: '0', padding: '15px', paddingTop: '80px' },
  mobileHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '15px', backgroundColor: white, boxShadow: '0 2px 4px rgba(0,0,0,0.1)', position: 'fixed', top: 0, right: 0, left: 0, zIndex: 999, height: '50px' },
  hamburgerButton: { background: 'none', border: 'none', fontSize: '28px', cursor: 'pointer', color: mainTextColor, fontFamily: "'Cairo Play', sans-serif" },
  mobileOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.5)', zIndex: 1050 },
  viewHeaderMobile: { flexDirection: 'column', alignItems: 'flex-start', gap: '20px' },
  viewHeaderActionsMobile: { flexDirection: 'column', width: '100%', gap: '10px', alignItems: 'stretch' },
  modalContentMobile: { width: '95%', padding: '20px', maxHeight: '85vh' },
  formRowMobile: { gridTemplateColumns: '1fr' },
  patientGridMobile: { gridTemplateColumns: '1fr' },
  patientDetailsGridMobile: { gridTemplateColumns: '1fr' },
  patientContactGridMobile: { gridTemplateColumns: '1fr' },
  dashboardGridMobile: { gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))' },
  dashboardTwoColumnGridMobile: { gridTemplateColumns: '1fr' },
  boardContainerMobile: { gridTemplateColumns: '1fr' },
  filtersContainerMobile: { flexDirection: 'column', alignItems: 'stretch' },
  fullWidth: { width: '100%' },
  appointmentItemMobile: { display: 'flex', flexDirection: 'column', gap: '12px', padding: '15px', alignItems: 'flex-start' },
  appointmentItemMobileHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', width: '100%' },
  scheduleModalItemMobile: { gridTemplateColumns: '1fr', gap: '10px' },
  calendarDayMobile: { minHeight: '60px' },
  calendarDayNumberMobile: { fontSize: '12px', fontFamily: "'Cairo Play', sans-serif", color: mainTextColor },
};